services:
  lotus-core-query:
    ports:
      - "${LOTUS_CORE_QUERY_PORT:-8201}:8001"

  lotus-core-ingestion:
    ports:
      - "${LOTUS_CORE_INGESTION_PORT:-8200}:8000"

  lotus-manage:
    ports:
      - "${LOTUS_MANAGE_PORT:-8000}:8000"

  lotus-performance:
    ports:
      - "${LOTUS_PERFORMANCE_PORT:-8002}:8000"

  lotus-report:
    ports:
      - "${LOTUS_REPORT_PORT:-8300}:8300"

  bff:
    ports:
      - "${BFF_PORT:-8100}:8100"

  ui:
    ports:
      - "${UI_PORT:-3000}:3000"

  prometheus:
    ports:
      - "${PROMETHEUS_PORT:-9190}:9090"

  grafana:
    ports:
      - "${GRAFANA_PORT:-3300}:3000"
